"""Criação das tabelas iniciais2

Revision ID: f95f72e1be0e
Revises: 
Create Date: 2025-11-21 11:53:53.080479

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f95f72e1be0e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Clients',
    sa.Column('ID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('contact', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_table('Movimentations',
    sa.Column('ID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('part_number', sa.String(), nullable=True),
    sa.Column('origin', sa.String(), nullable=True),
    sa.Column('employer_id', sa.Integer(), nullable=True),
    sa.Column('batch', sa.String(), nullable=True),
    sa.Column('qnty', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('destination', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_table('Scraps',
    sa.Column('ID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('part_number', sa.String(), nullable=True),
    sa.Column('batch', sa.String(), nullable=True),
    sa.Column('qnty', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('reason', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_table('Sectors',
    sa.Column('ID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sector', sa.String(), nullable=True),
    sa.Column('tag', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_table('Suppliers',
    sa.Column('ID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('contact', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_table('Components',
    sa.Column('ID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('part_number', sa.String(), nullable=True),
    sa.Column('description_material', sa.String(), nullable=True),
    sa.Column('supplier_ID', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['supplier_ID'], ['Suppliers.ID'], ),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_table('Employers',
    sa.Column('ID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('sector_ID', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['sector_ID'], ['Sectors.ID'], ),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_table('MachiningStock',
    sa.Column('ID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('part_number', sa.String(), nullable=True),
    sa.Column('batch', sa.String(), nullable=True),
    sa.Column('qnty', sa.Integer(), nullable=True),
    sa.Column('entry_date', sa.Date(), nullable=True),
    sa.Column('supplier_ID', sa.Integer(), nullable=True),
    sa.Column('race', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['supplier_ID'], ['Suppliers.ID'], ),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_table('Parts',
    sa.Column('ID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('part_number', sa.String(), nullable=True),
    sa.Column('description_parts', sa.String(), nullable=True),
    sa.Column('Clients_ID', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['Clients_ID'], ['Clients.ID'], ),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_table('Warehouse',
    sa.Column('ID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('part_number', sa.String(), nullable=True),
    sa.Column('batch', sa.String(), nullable=True),
    sa.Column('qnty', sa.Integer(), nullable=True),
    sa.Column('entry_date', sa.Date(), nullable=True),
    sa.Column('supplier_ID', sa.Integer(), nullable=True),
    sa.Column('date_last_movimentation', sa.Date(), nullable=True),
    sa.Column('supplier_batch', sa.String(), nullable=True),
    sa.Column('race', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['supplier_ID'], ['Suppliers.ID'], ),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_table('Machining_Production',
    sa.Column('serial_ID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('part_number', sa.String(), nullable=True),
    sa.Column('production_batch', sa.String(), nullable=True),
    sa.Column('employer', sa.String(), nullable=True),
    sa.Column('id_employer', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['id_employer'], ['Employers.ID'], ),
    sa.PrimaryKeyConstraint('serial_ID')
    )
    op.create_table('RelationPartsxComponents',
    sa.Column('ID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('part_ID', sa.Integer(), nullable=True),
    sa.Column('components_ID', sa.Integer(), nullable=True),
    sa.Column('comp_qnty', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['components_ID'], ['Components.ID'], ),
    sa.ForeignKeyConstraint(['part_ID'], ['Parts.ID'], ),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_table('Assembly_Production',
    sa.Column('ID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('part_number', sa.String(), nullable=True),
    sa.Column('components_ID', sa.Integer(), nullable=True),
    sa.Column('id_employer', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('initial_hour', sa.DateTime(), nullable=True),
    sa.Column('final_hour', sa.DateTime(), nullable=True),
    sa.Column('machine', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['components_ID'], ['Machining_Production.serial_ID'], ),
    sa.ForeignKeyConstraint(['id_employer'], ['Employers.ID'], ),
    sa.PrimaryKeyConstraint('ID')
    )
    
    # ### end Alembic commands ###


